---
- name: Create bucket
  hosts: localhost
  gather_facts: no

  vars:
    service_account_file: /home/sravangcp/gcp-key.json
    project: gcp-practice-secondary-prj
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
  - name: gcp bucket
    command: gsutil mb gs://bucket_5_25_345
    
  - name: create secreat
    shell: sh secreate.sh

  - name: apply kubectl
    commnad: kubectl apply -f deployment.yml
