---
- name: Create bucket
  hosts: localhost
  gather_facts: no
  environment:
    KUBECONFIG: "/home/sravangcp/.kube/config"

  vars:
    service_account_file: /home/sravangcp/gcp-key.json
    project: gcp-practice-secondary-prj
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  tasks:
  - name: gcp bucket
    command: gsutil mb gs://bucket_5_25_345
    
  - name: create secreat
    command: kubectl create secret generic my-app-sa-key --from-file gcp-key.json

  - name: apply kubectl
    commnad: kubectl apply -f deployment.yml
